layout_spectrum: 0.7532221
typography_spectrum: 0.4815766
color:
  saturation: 0.5088339
  lightness: 0.08122128
  brandStrength: 0.8038417
  rhythmicContrast: 0.2898497
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Fhloster Paradise
